# -*- mode: ruby -*-
# vi: set ft=ruby :
# Originally from https://github.com/rapid7/metasploitable3

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.box = "rapid7/metasploitable3-ub1404"
    ub1404.vm.hostname = "victim-ub1404"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    ub1404.vm.network "private_network", ip: '10.22.1.3', netmask: '255.255.255.0'

    ub1404.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.vmx["ethernet1.pcislotnumber"] = "33"
    end
  end

  config.vm.define "win2k8" do |win2k8|
    # Base configuration for the VM and provisioner
    win2k8.vm.box = "rapid7/metasploitable3-win2k8"
    win2k8.vm.hostname = "victim-win2k8"
    win2k8.vm.communicator = "winrm"
    win2k8.winrm.retry_limit = 60
    win2k8.winrm.retry_delay = 10

    win2k8.vm.network "private_network", ip: '10.22.1.5', netmask: '255.255.255.0'

    win2k8.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
      v.vmx["ethernet0.pcislotnumber"] = "33"
      # v.video_type = 'qxl'
      # v.input :type => "tablet", :bus => "usb"
      # v.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
      # v.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
      # v.graphics_type = "spice"

      # Enable Hyper-V enlightenments: https://blog.wikichoon.com/2014/07/enabling-hyper-v-enlightenments-with-kvm.html
      # v.hyperv_feature :name => 'stimer',  :state => 'on'
      # v.hyperv_feature :name => 'relaxed', :state => 'on'
      # v.hyperv_feature :name => 'vapic',   :state => 'on'
      # v.hyperv_feature :name => 'synic',   :state => 'on'
    end

    # Configure Firewall to open up vulnerable services
    case ENV['MS3_DIFFICULTY']
      when 'easy'
        win2k8.vm.provision :shell, inline: "C:\\startup\\disable_firewall.bat"
      else
        win2k8.vm.provision :shell, inline: "C:\\startup\\enable_firewall.bat"
        win2k8.vm.provision :shell, inline: "C:\\startup\\configure_firewall.bat"
    end

    # Insecure share from the Linux machine
    win2k8.vm.provision :shell, inline: "C:\\startup\\install_share_autorun.bat"
    win2k8.vm.provision :shell, inline: "C:\\startup\\setup_linux_share.bat"
    win2k8.vm.provision :shell, inline: "rm C:\\startup\\*" # Cleanup startup scripts
  end

  config.vm.define "kali_rolling_1" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "attacker-kali"
    kali.vm.provider "vmware_desktop" do |v|
      v.vmx["ethernet0.pcislotnumber"] = "160"
      v.memory = 2048
      v.gui = true
    end
    kali.vm.network "private_network", ip: "10.22.1.10", netmask: "255.255.255.0"
  end
end
